# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get mecha-device-test could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/mecha-device-test/0.1.0"
SRC_URI += "git://git@github.com/dhruveshb-mecha/mecha-device-test.git;protocol=ssh;nobranch=1;branch=display-test"
SRCREV = "1b84bf6edb7201bd0f31d4e0e9305c530d352130"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+1b84bf6edb"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/anstream/0.3.2 \
    crate://crates.io/anstyle-parse/0.2.0 \
    crate://crates.io/anstyle-query/1.0.0 \
    crate://crates.io/anstyle-wincon/1.0.1 \
    crate://crates.io/anstyle/1.0.0 \
    crate://crates.io/anyhow/1.0.71 \
    crate://crates.io/autocfg/1.1.0 \
    crate://crates.io/bitflags/1.3.2 \
    crate://crates.io/cc/1.0.79 \
    crate://crates.io/clap/4.3.3 \
    crate://crates.io/clap_builder/4.3.3 \
    crate://crates.io/clap_derive/4.3.2 \
    crate://crates.io/clap_lex/0.5.0 \
    crate://crates.io/colorchoice/1.0.0 \
    crate://crates.io/errno-dragonfly/0.1.2 \
    crate://crates.io/errno/0.3.1 \
    crate://crates.io/hashbrown/0.12.3 \
    crate://crates.io/heck/0.4.1 \
    crate://crates.io/hermit-abi/0.3.1 \
    crate://crates.io/indexmap/1.9.3 \
    crate://crates.io/io-lifetimes/1.0.11 \
    crate://crates.io/is-terminal/0.4.7 \
    crate://crates.io/itoa/1.0.6 \
    crate://crates.io/libc/0.2.146 \
    crate://crates.io/linux-raw-sys/0.3.8 \
    crate://crates.io/once_cell/1.18.0 \
    crate://crates.io/proc-macro2/1.0.60 \
    crate://crates.io/quote/1.0.28 \
    crate://crates.io/rustix/0.37.20 \
    crate://crates.io/ryu/1.0.13 \
    crate://crates.io/serde/1.0.164 \
    crate://crates.io/serde_derive/1.0.164 \
    crate://crates.io/serde_yaml/0.9.21 \
    crate://crates.io/strsim/0.10.0 \
    crate://crates.io/syn/2.0.18 \
    crate://crates.io/unicode-ident/1.0.9 \
    crate://crates.io/unsafe-libyaml/0.2.8 \
    crate://crates.io/utf8parse/0.2.1 \
    crate://crates.io/windows-sys/0.48.0 \
    crate://crates.io/windows-targets/0.48.0 \
    crate://crates.io/windows_aarch64_gnullvm/0.48.0 \
    crate://crates.io/windows_aarch64_msvc/0.48.0 \
    crate://crates.io/windows_i686_gnu/0.48.0 \
    crate://crates.io/windows_i686_msvc/0.48.0 \
    crate://crates.io/windows_x86_64_gnu/0.48.0 \
    crate://crates.io/windows_x86_64_gnullvm/0.48.0 \
    crate://crates.io/windows_x86_64_msvc/0.48.0 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

SUMMARY = "mecha-device-test"
HOMEPAGE = "https://github.com/dhruveshb-mecha/mecha-device-test"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include mecha-device-test-${PV}.inc
include mecha-device-test.inc
